name: poepapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.4+2

environment:
  sdk: '>=3.3.3 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0 
  shared_preferences: ^2.0.0 
  intl: ^0.19.0 
  confetti: ^0.6.0 
  fl_chart: ^0.68.0
  firebase_core: ^2.0.0 
  cloud_firestore: ^4.0.0
  uuid: ^4.0.0 
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 

flutter:
  uses-material-design: true