// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcYHU06Pnbub8A945zUtP83A3ufThqPsU',
    appId: '1:1075749085184:web:6d28aa192391153f1978e5',
    messagingSenderId: '1075749085184',
    projectId: 'poepapp-e3566',
    authDomain: 'poepapp-e3566.firebaseapp.com',
    storageBucket: 'poepapp-e3566.firebasestorage.app',
    measurementId: 'G-HEPTD2HT19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWR7jZMeUqFc0hx9VYGKZr19yMUdmzGx8',
    appId: '1:1075749085184:android:8b0ebf36f52ea23d1978e5',
    messagingSenderId: '1075749085184',
    projectId: 'poepapp-e3566',
    storageBucket: 'poepapp-e3566.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPtP7AzRCt-VZtWYwH6dEmELyr5mki16E',
    appId: '1:1075749085184:ios:d85d6a74fbcb88bd1978e5',
    messagingSenderId: '1075749085184',
    projectId: 'poepapp-e3566',
    storageBucket: 'poepapp-e3566.firebasestorage.app',
    iosBundleId: 'com.example.poepapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPtP7AzRCt-VZtWYwH6dEmELyr5mki16E',
    appId: '1:1075749085184:ios:d85d6a74fbcb88bd1978e5',
    messagingSenderId: '1075749085184',
    projectId: 'poepapp-e3566',
    storageBucket: 'poepapp-e3566.firebasestorage.app',
    iosBundleId: 'com.example.poepapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcYHU06Pnbub8A945zUtP83A3ufThqPsU',
    appId: '1:1075749085184:web:06bbf0e0b6b17fcf1978e5',
    messagingSenderId: '1075749085184',
    projectId: 'poepapp-e3566',
    authDomain: 'poepapp-e3566.firebaseapp.com',
    storageBucket: 'poepapp-e3566.firebasestorage.app',
    measurementId: 'G-XP4YZR9ZHW',
  );
}
